export const workspace = {
  name: 'AI 协作项目驾驶舱',
  subtitle: '多项目交付总览 / 需求治理 / 执行收口',
  owner: '交付治理组',
  updatedAt: '2026-04-09 22:18',
  activeProjects: 2,
  blockedProjects: 1,
  health: '需要关注',
};

export const stageMeta = [
  {
    key: 'bootstrap',
    label: '底座',
    title: '仓库底座初始化',
    short: '就绪',
    gate: '底座健康检查',
    output: 'AGENTS / PROJECT_CONTEXT / .ai',
    color: 'cyan',
  },
  {
    key: 'requirement',
    label: '需求治理',
    title: '需求治理',
    short: '交接',
    gate: '人工审核门',
    output: '需求池 / 任务看板 / task memory',
    color: 'amber',
  },
  {
    key: 'execution',
    label: '执行收口',
    title: '执行收口',
    short: '推进',
    gate: '显式开工 + 发布闸门',
    output: '代码 / 验证 / 证据 / 状态',
    color: 'emerald',
  },
];

export const projects = [
  {
    id: 'hrms',
    name: '人力资源管理系统',
    alias: 'HRMS',
    domain: '组织 / 员工 / 考勤',
    owner: '王敏',
    lead: '产品 + 前端 + 后端',
    iteration: 'V2.4 体验重构',
    release: '2026 Q2 - Iteration 3',
    stage: 'execution',
    gateStatus: '进行中',
    health: '良好',
    risk: '低',
    lastUpdated: '2026-04-09 22:12',
    summary:
      '围绕员工档案、组织架构、考勤提醒三个重点模块推进交付收口，当前已进入执行阶段。',
    metrics: {
      totalTasks: 8,
      doing: 3,
      blocked: 1,
      review: 2,
      done: 2,
      evidenceCoverage: 78,
      releaseGate: '待验证',
    },
    stageStates: {
      bootstrap: 'done',
      requirement: 'done',
      execution: 'current',
    },
    currentTask: 'TASK-204',
    currentFocus: '考勤异常提醒规则收口',
    blocker:
      '考勤异常提醒的阈值规则需要业务再确认，验证样例待补齐。',
    tasks: [
      {
        id: 'TASK-201',
        reqId: 'REQ-104',
        title: '员工档案批量导入',
        status: 'done',
        owner: '林澈',
        priority: 'P2',
        blocker: '',
        next: '已完成验收，归档证据',
        evidence: '导入校验记录 / 测试通过',
      },
      {
        id: 'TASK-202',
        reqId: 'REQ-104',
        title: '组织架构拖拽排序',
        status: 'review',
        owner: '周南',
        priority: 'P1',
        blocker: '',
        next: '等待产品确认边界文案',
        evidence: 'UI 回归截图 / 提交记录',
      },
      {
        id: 'TASK-203',
        reqId: 'REQ-105',
        title: '离职流程审批',
        status: 'blocked',
        owner: '唐可',
        priority: 'P1',
        blocker: '审批节点顺序待业务确认',
        next: '补确认单后再恢复',
        evidence: '阻塞说明已写入 inbox',
      },
      {
        id: 'TASK-204',
        reqId: 'REQ-105',
        title: '考勤异常提醒',
        status: 'doing',
        owner: '顾然',
        priority: 'P0',
        blocker: '规则口径待确认',
        next: '补阈值样例并继续验证',
        evidence: '本地验证中',
      },
      {
        id: 'TASK-205',
        reqId: 'REQ-106',
        title: '权限矩阵优化',
        status: 'doing',
        owner: '孟远',
        priority: 'P2',
        blocker: '',
        next: '完成权限树边界回归',
        evidence: '接口联调已完成 70%',
      },
      {
        id: 'TASK-206',
        reqId: 'REQ-106',
        title: '员工证件信息加密',
        status: 'todo',
        owner: '待分配',
        priority: 'P1',
        blocker: '',
        next: '等待本轮排期',
        evidence: '尚未开始',
      },
      {
        id: 'TASK-207',
        reqId: 'REQ-106',
        title: '合同附件提醒',
        status: 'review',
        owner: '陈野',
        priority: 'P2',
        blocker: '',
        next: '补充测试记录后合并',
        evidence: '验证记录草稿已写',
      },
      {
        id: 'TASK-208',
        reqId: 'REQ-107',
        title: '员工画像概览',
        status: 'done',
        owner: '韩歌',
        priority: 'P3',
        blocker: '',
        next: '已完成',
        evidence: '发布说明 / 快照归档',
      },
    ],
    evidence: [
      {
        title: '验证记录',
        value: '6 条',
        detail: '最近一次覆盖主流程与边界场景',
      },
      {
        title: '证据完整度',
        value: '78%',
        detail: '缺少两条阻塞任务的最终验证记录',
      },
      {
        title: '发布闸门',
        value: '待验证',
        detail: '通过后才能进入收口归档',
      },
    ],
    risks: [
      '考勤异常提醒缺少最终规则确认',
      '离职流程审批需避免绕过人工审核门',
      '证据回写仍有两项待补齐',
    ],
    timeline: [
      {
        time: '22:12',
        label: '更新任务看板',
        desc: 'TASK-204 进入 doing，等待规则口径确认。',
      },
      {
        time: '21:48',
        label: '回写验证记录',
        desc: '组织架构拖拽排序进入 review。',
      },
      {
        time: '20:30',
        label: '完成执行开工',
        desc: '本轮执行从 requirement 交接进入收口阶段。',
      },
    ],
    members: ['王敏', '林澈', '周南', '唐可', '顾然'],
  },
  {
    id: 'cms',
    name: '稿件管理系统',
    alias: 'CMS',
    domain: '投稿 / 审稿 / 版本追踪',
    owner: '赵雨',
    lead: '产品 + 设计 + 平台',
    iteration: 'V1.9 审稿流改造',
    release: '2026 Q2 - Iteration 2',
    stage: 'requirement',
    gateStatus: '待人工审核',
    health: '观察中',
    risk: '中',
    lastUpdated: '2026-04-09 21:56',
    summary:
      '当前正在沉淀稿件流转、审稿人分配和版本追踪三块需求，处于需求治理收口阶段。',
    metrics: {
      totalTasks: 6,
      doing: 2,
      blocked: 1,
      review: 1,
      done: 2,
      evidenceCoverage: 63,
      releaseGate: '未进入',
    },
    stageStates: {
      bootstrap: 'done',
      requirement: 'current',
      execution: 'todo',
    },
    currentTask: 'REQ-209',
    currentFocus: '稿件流转与审稿人规则治理',
    blocker: '审稿人轮转规则尚未冻结，等待产品签字。',
    tasks: [
      {
        id: 'TASK-311',
        reqId: 'REQ-209',
        title: '稿件流转看板',
        status: 'todo',
        owner: '待分配',
        priority: 'P1',
        blocker: '',
        next: '需要先冻结字段口径',
        evidence: '需求草案',
      },
      {
        id: 'TASK-312',
        reqId: 'REQ-209',
        title: '审稿人分配规则',
        status: 'doing',
        owner: '许言',
        priority: 'P0',
        blocker: '待确认轮转策略',
        next: '补充业务规则后入看板',
        evidence: '规则草图 / 追溯表',
      },
      {
        id: 'TASK-313',
        reqId: 'REQ-210',
        title: '稿件版本追踪',
        status: 'review',
        owner: '陆行',
        priority: 'P2',
        blocker: '',
        next: '等待评审结论',
        evidence: 'PRD 追溯已更新',
      },
      {
        id: 'TASK-314',
        reqId: 'REQ-210',
        title: '自动提醒策略',
        status: 'blocked',
        owner: '乔安',
        priority: 'P1',
        blocker: '通知节奏待产品确认',
        next: '补交接说明后恢复',
        evidence: '阻塞说明已登记',
      },
      {
        id: 'TASK-315',
        reqId: 'REQ-211',
        title: '历史稿件迁移',
        status: 'done',
        owner: '高远',
        priority: 'P3',
        blocker: '',
        next: '已完成',
        evidence: '迁移报告 / 验收通过',
      },
      {
        id: 'TASK-316',
        reqId: 'REQ-211',
        title: '评论内容脱敏',
        status: 'done',
        owner: '夏知',
        priority: 'P2',
        blocker: '',
        next: '归档完成',
        evidence: '脱敏测试通过',
      },
    ],
    evidence: [
      {
        title: '需求交接',
        value: '待审核',
        detail: '还不能直接进入 execution',
      },
      {
        title: '任务看板',
        value: '6 条',
        detail: '正在同步 task memory 与追溯表',
      },
      {
        title: '证据完整度',
        value: '63%',
        detail: '尚缺审稿规则冻结后的验证材料',
      },
    ],
    risks: [
      '审稿人轮转规则没有冻结',
      '自动提醒策略可能影响交接节奏',
      '需求包需要补一份最终确认材料',
    ],
    timeline: [
      {
        time: '21:56',
        label: '更新需求包',
        desc: '稿件流转看板草案已补齐。',
      },
      {
        time: '21:08',
        label: '同步任务索引',
        desc: 'TASK-312、TASK-313 状态有变化。',
      },
      {
        time: '20:15',
        label: '停在人工审核门',
        desc: '本轮 requirement 已收口，等待确认后再开工。',
      },
    ],
    members: ['赵雨', '许言', '陆行', '乔安', '高远'],
  },
];
